export enum NotificationType {
  FAMILY_INVITATION_SENT = 'FAMILY_INVITATION_SENT',
  FAMILY_INVITATION_RECEIVED = 'FAMILY_INVITATION_RECEIVED',
  FAMILY_INVITATION_ACCEPTED = 'FAMILY_INVITATION_ACCEPTED',
  FAMILY_INVITATION_DECLINED = 'FAMILY_INVITATION_DECLINED',
  FAMILY_MEMBER_JOINED = 'FAMILY_MEMBER_JOINED',
  FAMILY_MEMBER_LEFT = 'FAMILY_MEMBER_LEFT',
  FAMILY_TRANSACTION_CREATED = 'FAMILY_TRANSACTION_CREATED',
  TRANSACTION_MILESTONE_BUDGET_ALERT = 'TRANSACTION_MILESTONE_BUDGET_ALERT',
  TRANSACTION_MILESTONE_SPENDING_LIMIT = 'TRANSACTION_MILESTONE_SPENDING_LIMIT',
  RECEIPT_PROCESSING_COMPLETE = 'RECEIPT_PROCESSING_COMPLETE',
}

export enum NotificationPriority {
  LOW = 'LOW',
  MEDIUM = 'MEDIUM',
  HIGH = 'HIGH',
  URGENT = 'URGENT',
}

export enum DeliveryMethod {
  PUSH = 'PUSH',
  IN_APP = 'IN_APP',
  TOAST = 'TOAST',
}
