import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#fff",
    padding: 16,
  },
  section: {
    marginBottom: 24,
  },
  sectionTitle: {
    fontSize: 18,
    fontWeight: "600",
    marginBottom: 12,
    color: "#333",
  },
  subSectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    marginBottom: 12,
    color: "#333",
  },
  input: {
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    padding: 12,
    marginBottom: 12,
    fontSize: 16,
    backgroundColor: "#fff",
  },
  dropdown: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    marginTop: -8,
    marginBottom: 12,
    maxHeight: 200,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  dropdownLoader: {
    padding: 16,
  },
  dropdownList: {
    maxHeight: 200,
  },
  dropdownItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  dropdownItemText: {
    fontSize: 16,
    color: "#333",
  },
  dropdownItemPrice: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
  },
  noResultsText: {
    padding: 16,
    fontSize: 14,
    color: "#999",
    textAlign: "center",
  },
  createOption: {
    backgroundColor: "#f8f9fa",
    borderTopWidth: 2,
    borderTopColor: "#007AFF",
    borderBottomWidth: 0,
  },
  createOptionText: {
    fontSize: 15,
    color: "#007AFF",
    fontWeight: "600",
  },
  selectedCategoryContainer: {
    marginTop: 8,
    marginBottom: 16,
  },
  selectedCategoryLabel: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
  },
  selectedCategoryChip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#007AFF",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
  },
  selectedCategoryText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "600",
  },
  clearButton: {
    fontSize: 20,
    color: "#fff",
    fontWeight: "bold",
    paddingLeft: 12,
  },
  storeDropdown: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#ddd",
    borderRadius: 8,
    maxHeight: 150,
    marginTop: -8,
  },
  storeItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  storeText: {
    fontSize: 16,
    fontWeight: "500",
  },
  storeLocationText: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
  },
  addNewStoreOption: {
    backgroundColor: "#f8f9fa",
    borderTopWidth: 2,
    borderTopColor: "#007AFF",
  },
  addNewStoreText: {
    fontSize: 15,
    color: "#007AFF",
    fontWeight: "600",
  },
  selectedStoreContainer: {
    marginTop: 8,
    marginBottom: 16,
  },
  selectedStoreLabel: {
    fontSize: 14,
    color: "#666",
    marginBottom: 8,
  },
  selectedStoreChip: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#007AFF",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
  },
  selectedStoreText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "600",
  },
  selectedStoreLocationText: {
    fontSize: 14,
    color: "#e8f4ff",
    marginTop: 4,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
  },
  modalContent: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 24,
    width: "85%",
    maxWidth: 400,
  },
  modalTitle: {
    fontSize: 20,
    fontWeight: "600",
    marginBottom: 20,
    color: "#333",
    textAlign: "center",
  },
  modalButtons: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 8,
    gap: 12,
  },
  modalButton: {
    flex: 1,
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  modalCancelButton: {
    backgroundColor: "#f0f0f0",
  },
  modalCancelButtonText: {
    color: "#333",
    fontSize: 16,
    fontWeight: "600",
  },
  modalCreateButton: {
    backgroundColor: "#007AFF",
  },
  modalCreateButtonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  formSection: {
    marginTop: 16,
  },
  itemCard: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#f5f5f5",
    borderRadius: 8,
    marginBottom: 8,
  },
  itemInfo: {
    flex: 1,
  },
  itemName: {
    fontSize: 16,
    fontWeight: "500",
  },
  itemPrice: {
    fontSize: 14,
    color: "#666",
    marginTop: 4,
  },
  removeButton: {
    color: "#ff3b30",
    fontWeight: "600",
  },
  label: {
    fontSize: 14,
    fontWeight: "500",
    marginBottom: 8,
    marginTop: 12,
  },
  categoryChip: {
    paddingHorizontal: 16,
    paddingVertical: 8,
    borderRadius: 20,
    borderWidth: 1,
    borderColor: "#007AFF",
    marginRight: 8,
    marginBottom: 12,
  },
  categoryChipSelected: {
    backgroundColor: "#007AFF",
  },
  categoryChipText: {
    color: "#007AFF",
    fontSize: 14,
  },
  categoryChipTextSelected: {
    color: "#fff",
  },
  addButton: {
    backgroundColor: "#34C759",
    padding: 12,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 12,
  },
  submitButton: {
    backgroundColor: "#007AFF",
    padding: 16,
    borderRadius: 8,
    alignItems: "center",
    marginTop: 16,
    marginBottom: 32,
  },
  buttonText: {
    color: "#fff",
    fontSize: 16,
    fontWeight: "600",
  },
  button: {
    flex: 1,
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
  },
  cancelButton: {
    backgroundColor: "#f0f0f0",
  },
  cancelButtonText: {
    color: "#333",
    fontSize: 16,
    fontWeight: "600",
  },
  createButton: {
    backgroundColor: "#007AFF",
  },
  parentCategorySelector: {
    marginBottom: 16,
    maxHeight: 150,
  },
  selectedParentContainer: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    backgroundColor: "#007AFF",
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderRadius: 8,
  },
  selectedParentText: {
    fontSize: 16,
    color: "#fff",
    fontWeight: "600",
  },
  parentCategoryItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
    backgroundColor: "#f8f9fa",
  },
  parentCategoryText: {
    fontSize: 16,
    color: "#333",
  },
  parentCategoryList: {
    maxHeight: 150,
  },
});
